routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    ['middleware' => 'locale'],
    function () {
        Route::get('change-language/{language}', 'changeLanguageController@changeLanguage')
            ->name('user.change-language');
    }
);
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact');


Auth::routes(
    [
        'verify' => false,
    ]
);

Route::name('admin.')->prefix('admin')->middleware(['auth', 'can:accessAdmin'])->group(
    function () {
        Route::get('dashboard', 'DashboardController@index')->name('index');
        Route::resource('category', 'CategoryController');
        Route::resource('banner', 'BannerController');
        Route::resource('product', 'ProductController');
        Route::resource('deal', 'DealController');
        Route::resource('user', 'Auth\UserController');
        Route::resource('order', 'OrderController');
        Route::resource('review', 'ReviewController');
    }
);
route::get('product/show/{id}', 'ProductController@show')->name('product.show');
route::get('review', 'ReviewController@index')->name('pro222duct.show');
route::get('product/show-all', 'ProductController@showAll')->name('product.showAll');
route::get('category/show/{id}', 'CategoryController@show')->name('category.show');
Route::resource('account', 'Auth\AccountController');
Route::get('account/{id}/changePass', 'Auth\AccountController@changePass')->name('account.changePass');
Route::post('account/{id}/updatePass', 'Auth\AccountController@updatePass')->name('account.updatePass');
Route::post('add-cart', 'CartController@save_cart')->name('addCart');
Route::get('/search', 'HomeController@search');
Route::get('show-cart', 'CartController@show_cart')->name('showCart');
Route::post('update-qty-cart{id}', 'CartController@update_quantity')->name('updateCart');
Route::get('delete-cart/{rowId}', 'CartController@delete_cart')->name('deleteCart');
Route::get('order/create', 'OrderController@create')->name('order.create');
Route::post('order/store', 'OrderController@store')->name('order.store');
Route::post('review/store', 'ReviewController@store')->name('review.store');
Route::get('/filter', 'HomeController@filter');
Route::get('order/{id}/history', 'OrderController@history')->name('order.history');
Route::post('order/cancel/{id}', 'OrderController@cancel')->name('order.cancel');
Route::get('order/history-detail/{id}', 'OrderController@historyDetail')->name('order.history-detail');

Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/{provider}/callback', 'SocialController@callback');

Route::post('add-wishlist', 'WishlistController@save_wishlist')->name('addWish');
Route::get('show-wishlist/{id}', 'WishlistController@show_wishlist')->name('showWish');
Route::post('delete-wishlist/{rowId}', 'WishlistController@delete_wishlist')->name('deleteWish');

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Review;
use App\Product;
use Illuminate\Support\Facades\Auth;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reviews = Product::with('reviews')->get();

        return view('reviews.view', compact('reviews'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Review::create([
            'user_id' => Auth::user()->user_id,
            'pro_id' => $request->input('pro_id'),
            'comment' => $request->input('comment'),
            'rate' => $request->input('rate'),
        ]);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $rev = Product::findOrFail($id);

        return view('reviews.show', compact('rev'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $review = Review::findOrFail($id);
        $review->delete();

        return redirect()->back();
    }
}

resources/views/reviews/show.blade.php
@extends('layouts.admin')
@section('title', trans('admin.title'))
@section('content')
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>{{ $rev->pro_name }}</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 ">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>@lang('admin.reviews.rev_view')</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                        aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    {{-- <div class="dropdown-menu"
                                        aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#">Settings 1</a>
                                        <a class="dropdown-item" href="#">Settings 2</a>
                                    </div> --}}
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card-box table-responsive">

                                        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                                            <thead>
                                                <tr class="text-center">
                                                    <th>@lang('admin.user.username')</th>
                                                    <th>@lang('admin.reviews.cmt')</th>
                                                    <th>@lang('admin.reviews.rate')</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($rev->reviews as $r)
                                                <tr class="text-center">
                                                    <th>{{ $r->user->username }}</th>
                                                    <th>{{ $r->comment}}</th>
                                                    <th>{{ $r->rate}}</th>
                                                    <th>
                                                        <form action="{{ route('admin.review.destroy', $r->rev_id) }}" method="post">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit">@lang('admin.action.delete')</button>
                                                        </form>
                                                    </th>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/reviews/view.blade.php
@extends('layouts.admin')
@section('title', trans('admin.title'))
@section('content')
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>@lang('admin.reviews.rev_manage')</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 ">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>@lang('admin.reviews.rev_view')</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                        aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    {{-- <div class="dropdown-menu"
                                        aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#">Settings 1</a>
                                        <a class="dropdown-item" href="#">Settings 2</a>
                                    </div> --}}
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card-box table-responsive">

                                        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                                            <thead>
                                                <tr class="text-center">
                                                    <th>@lang('admin.products.pro_name')</th>
                                                    <th>@lang('admin.reviews.num_rev')</th>
                                                    <th>@lang('admin.action.show')</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($reviews as $rev)
                                                @if($rev->reviews->count() > 0)
                                                <tr class="text-center">
                                                    <th class="text-left">{{ $rev->pro_name }}</th>
                                                    <th>{{ $rev->reviews->count() }}</th>
                                                    <th><a href="{{ route('admin.review.show', $rev->pro_id) }}">@lang('main.see_more')</a></th>
                                                </tr>
                                                @endif
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection