routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    ['middleware' => 'locale'],
    function () {
        Route::get('change-language/{language}', 'changeLanguageController@changeLanguage')
            ->name('user.change-language');
    }
);
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact');


Auth::routes(
    [
        'verify' => false,
    ]
);

Route::name('admin.')->prefix('admin')->middleware(['auth', 'can:accessAdmin'])->group(
    function () {
        Route::get('dashboard', 'DashboardController@index')->name('index');
        Route::resource('category', 'CategoryController');
        Route::resource('banner', 'BannerController');
        Route::resource('product', 'ProductController');
        Route::resource('deal', 'DealController');
        Route::resource('user', 'Auth\UserController');
        Route::resource('order', 'OrderController');
        Route::resource('review', 'ReviewController');
    }
);
route::get('product/show/{id}', 'ProductController@show')->name('product.show');
route::get('review', 'ReviewController@index')->name('pro222duct.show');
route::get('product/show-all', 'ProductController@showAll')->name('product.showAll');
route::get('category/show/{id}', 'CategoryController@show')->name('category.show');
Route::resource('account', 'Auth\AccountController');
Route::get('account/{id}/changePass', 'Auth\AccountController@changePass')->name('account.changePass');
Route::post('account/{id}/updatePass', 'Auth\AccountController@updatePass')->name('account.updatePass');
Route::post('add-cart', 'CartController@save_cart')->name('addCart');
Route::get('/search', 'HomeController@search');
Route::get('show-cart', 'CartController@show_cart')->name('showCart');
Route::post('update-qty-cart{id}', 'CartController@update_quantity')->name('updateCart');
Route::get('delete-cart/{rowId}', 'CartController@delete_cart')->name('deleteCart');
Route::get('order/create', 'OrderController@create')->name('order.create');
Route::post('order/store', 'OrderController@store')->name('order.store');
Route::post('review/store', 'ReviewController@store')->name('review.store');
Route::get('/filter', 'HomeController@filter');
Route::get('order/{id}/history', 'OrderController@history')->name('order.history');
Route::post('order/cancel/{id}', 'OrderController@cancel')->name('order.cancel');
Route::get('order/history-detail/{id}', 'OrderController@historyDetail')->name('order.history-detail');

Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/{provider}/callback', 'SocialController@callback');

Route::post('add-wishlist', 'WishlistController@save_wishlist')->name('addWish');
Route::get('show-wishlist/{id}', 'WishlistController@show_wishlist')->name('showWish');
Route::post('delete-wishlist/{rowId}', 'WishlistController@delete_wishlist')->name('deleteWish');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Product;

class Category extends Model
{
    protected $primaryKey = 'cate_id';

    protected $fillable = [
        'cate_name',
        'cate_desc',
        'cate_logo',
        'cate_image',
        'parent_id',
    ];

    public function products()
    {
        return $this->hasMany(Product::class, 'cate_id');
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }
    
    public function parent()
    {
        return $this->belongsTo(Category::class, 'cate_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->has('search')){
            $search = $request->input('search');
            $categories = Category::search($search)->paginate(10);

            return view('category.view', compact('categories'));
        }
        $categories = Category::whereNull('parent_id')->with('children')->paginate(10);

        return view('category.view', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::whereNull('parent_id')->get();

        return view('category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fileLogo = $request->file('cate_logo');
        $fileNameLogo = uniqid() . '_' . $fileLogo->getClientOriginalName();
        $fileLogo->move('images/categories/logos', $fileNameLogo);
        $fileImage = $request->file('cate_image');
        $fileNameImage = uniqid() . '_' . $fileImage->getClientOriginalName();
        $fileImage->move('images/categories/images', $fileNameImage);
        Category::create([
            'cate_name' => $request->input('cate_name'),
            'cate_desc' => $request->input('cate_desc'),
            'cate_logo' => $fileNameLogo,
            'cate_image' => $fileNameImage,
            'parent_id' => $request->input('parent_id'),
        ]);

        return redirect()->route('admin.category.index')->with('add_success', trans('admin.message.add_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($cateId, Request $request)
    {
        if ($request->has('min_pri') && $request->has('max_pri')) {
            $min = $request->input('min_pri');
            $max = $request->input('max_pri');
            $categories = Category::all();
            $cate = Category::findOrFail($cateId);
            $products = Product::where('cate_id', $cateId)->pricebetween($min, $max)->paginate(12);
            return view('category.show', compact('cate', 'categories', 'products'));
        }
        $filter = $request->input('filter');
        switch ($filter) {
            case 'newest':
                $categories = Category::all();
                $products = Product::where('cate_id', $cateId)->newest()->paginate(12);
                $cate = Category::findOrFail($cateId);
                return view('category.show', compact('cate', 'categories', 'products'));
            break;
            case 'viewest':
                $categories = Category::all();
                $products = Product::where('cate_id', $cateId)->viewest()->paginate(12);
                $cate = Category::findOrFail($cateId);
                return view('category.show', compact('cate', 'categories', 'products'));
            break;
            case 'best_discount':
                $categories = Category::all();
                $products = Product::where('cate_id', $cateId)->viewest()->paginate(12);
                $cate = Category::findOrFail($cateId);
                return view('category.show', compact('cate', 'categories', 'products'));
            break;
            case 'saling':
                $categories = Category::all();
                $products = Product::where('cate_id', $cateId)->saling()->paginate(12);
                $cate = Category::findOrFail($cateId);
                return view('category.show', compact('cate', 'categories', 'products'));
            break;
            case 'Ascending':
                $categories = Category::all();
                $products = Product::where('cate_id', $cateId)->ascending()->paginate(12);
                $cate = Category::findOrFail($cateId);
                return view('category.show', compact('cate', 'categories', 'products'));
            break;
            case 'Decrease':
                $categories = Category::all();
                $products = Product::where('cate_id', $cateId)->decrease()->paginate(12);
                $cate = Category::findOrFail($cateId);
                return view('category.show', compact('cate', 'categories', 'products'));
            break;
            default:
                $categories = Category::all();
                $products = Product::where('cate_id', $cateId)->nameproduct($filter)->paginate(12);
                $cate = Category::findOrFail($cateId);
                return view('category.show', compact('cate', 'categories', 'products'));
            break;
        };
        $categories = Category::all();
        $cate = Category::findOrFail($cateId);
        $products = Product::where('cate_id', $cateId)->paginate(12);

        return view('category.show', compact('cate', 'categories', 'products'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($cateId)
    {
        $cate = Category::findOrFail($cateId);
        $categories = Category::whereNull('parent_id')->get();

        return view('category.edit', compact('cate', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $cateId)
    {
        $cate = Category::findOrFail($cateId);

        $fileLogo = $request->file('cate_logo');
        $fileNameLogo = uniqid() . '_' . $fileLogo->getClientOriginalName();
        $fileLogo->move('images/categories/logos', $fileNameLogo);
        $fileImage = $request->file('cate_image');
        $fileNameImage = uniqid() . '_' . $fileImage->getClientOriginalName();
        $fileImage->move('images/categories/images', $fileNameImage);

        $cate->cate_name = $request->input('cate_name');
        $cate->cate_desc = $request->input('cate_desc');
        $cate->cate_image = $fileNameImage;
        $cate->cate_logo = $fileNameLogo;
        $cate->parent_id = $request->input('parent_id');
        $cate->save();

        return redirect()->route('admin.category.index')->with('update_success', trans('admin.message.update_success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($cateId)
    {
        $cate = Category::findOrFail($cateId);
        if($cate->parent_id == null){
            $cate->children()->delete();
            $cate->products()->delete();
            $cate->delete();
        }

        return redirect()->route('admin.category.index')->with('del_success', trans('admin.message.del_success'));
    }
}

resources/views/category/view.blade.php
@extends('layouts.admin')
@section('content')
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>@lang('admin.categories.cate_manage')</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 ">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>@lang('admin.categories.hihi')</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                        aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    {{-- <div class="dropdown-menu"
                                        aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#">Settings 1</a>
                                        <a class="dropdown-item" href="#">Settings 2</a>
                                    </div> --}}
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="row">
                                <div class="col-sm-12">
                                    @if (session()->has('del_success'))
                                        <div class="text-success" style="text-shadow: 0 0 1px black;">
                                            {{ session()->get('del_success') }}</div>
                                    @elseif( session()->has('add_success'))
                                        <div class="atext-success" style="text-shadow: 0 0 1px black;">
                                            {{ session()->get('add_success') }}</div>
                                    @elseif (session()->has('update_success'))
                                        <div class="text-success" style="text-shadow: 0 0 1px black;">
                                            {{ session()->get('update_success') }}</div>
                                    @endif
                                    <div class="card-box table-responsive">

                                        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th>@lang('admin.categories.id')</th>
                                                    <th>@lang('admin.categories.cate_name')</th>
                                                    <th>@lang('admin.categories.cate_image')</th>
                                                    <th>@lang('admin.categories.cate_logo')</th>
                                                    <th>@lang('admin.categories.cate_desc')</th>
                                                    <th colspan="2" class="text-center">
                                                        <a href="{{ route('admin.category.create') }}"
                                                            class="btn btn-outline-success">@lang('admin.action.create')
                                                        </a>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($categories as $cate)
                                                    <tr>
                                                        <td>{{ $cate->cate_id }}</td>
                                                        <td>{{ $cate->cate_name }}</td>
                                                        <td>
                                                            @if ($cate->cate_image == null)
                                                                <img class="img-thumbnail"
                                                                    style="width: 100px; height:100px;"
                                                                    src="https://logos.textgiraffe.com/logos/logo-name/Cate-designstyle-smoothie-m.png"
                                                                    alt="">
                                                            @else
                                                                <img class="img-thumbnail"
                                                                    style="width: 100px; height:100px;"
                                                                    src="images/categories/images/{{ $cate->cate_image }}"
                                                                    alt="">
                                                            @endif
                                                        </td>
                                                        <td>
                                                            @if ($cate->cate_logo == null)
                                                                <img class="img-thumbnail"
                                                                    style="width: 100px; height:100px;"
                                                                    src="https://logos.textgiraffe.com/logos/logo-name/Cate-designstyle-smoothie-m.png"
                                                                    alt="">
                                                            @else
                                                                <img class="img-thumbnail"
                                                                    style="width: 100px; height:100px;"
                                                                    src="images/categories/logos/{{ $cate->cate_logo }}"
                                                                    alt="">
                                                            @endif
                                                        </td>
                                                        <td>{{ $cate->cate_desc }}</td>
                                                        <td class="text-center"><a
                                                                href="{{ route('admin.category.edit', $cate->cate_id) }}"
                                                                class="btn btn-outline-info btn-xs"><i
                                                                    class="fa fa-pencil"></i> @lang('admin.action.edit')
                                                            </a></td>
                                                        <td class="text-center">
                                                            <form
                                                                action="{{ route('admin.category.destroy', $cate->cate_id) }}"
                                                                method="post">
                                                                @csrf
                                                                @method('DELETE')
                                                                <button type="submit" class="btn btn-outline-danger"><i
                                                                        class="fa fa-trash-o"></i>
                                                                    @lang('admin.action.delete') </button>
                                                            </form>
                                                        </td>
                                                    </tr>
                                                    @foreach ($cate->children as $key)
                                                        <tr>
                                                            <td>{{ $key->cate_id }}</td>
                                                            <td>―― {{ $key->cate_name }}</td>
                                                            <td>
                                                                @if ($key->cate_image == null)
                                                                    <img class="img-thumbnail"
                                                                        style="width: 100px; height:100px;"
                                                                        src="https://logos.textgiraffe.com/logos/logo-name/Cate-designstyle-smoothie-m.png"
                                                                        alt="">
                                                                @else
                                                                    <img class="img-thumbnail"
                                                                        style="width: 100px; height:100px;"
                                                                        src="images/categories/images/{{ $key->cate_image }}"
                                                                        alt="">
                                                                @endif
                                                            </td>
                                                            <td>
                                                                @if ($key->cate_logo == null)
                                                                    <img class="img-thumbnail"
                                                                        style="width: 100px; height:100px;"
                                                                        src="https://logos.textgiraffe.com/logos/logo-name/Cate-designstyle-smoothie-m.png"
                                                                        alt="">
                                                                @else
                                                                    <img class="img-thumbnail"
                                                                        style="width: 100px; height:100px;"
                                                                        src="images/categories/logos/{{ $cate->cate_logo }}"
                                                                        alt="">
                                                                @endif
                                                            </td>
                                                            <td>{{ $key->cate_desc }}</td>
                                                            <td class="text-center"><a
                                                                    href="{{ route('admin.category.edit', $key->cate_id) }}"
                                                                    class="btn btn-outline-info btn-xs"><i
                                                                        class="fa fa-pencil"></i> @lang('admin.action.edit')
                                                                </a></td>
                                                            <td class="text-center">
                                                                <form
                                                                    action="{{ route('admin.category.destroy', $key->cate_id) }}"
                                                                    method="post">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                    <button type="submit"
                                                                        onclick="return confirm('Bạn có chắc muốn xóa?');"
                                                                        class="btn btn-outline-danger"><i
                                                                            class="fa fa-trash-o"></i>
                                                                        @lang('admin.action.delete') </button>
                                                                </form>
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                @endforeach
                                            </tbody>
                                        </table>
                                        {{ $categories->links() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection