routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    ['middleware' => 'locale'],
    function () {
        Route::get('change-language/{language}', 'changeLanguageController@changeLanguage')
            ->name('user.change-language');
    }
);
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact');


Auth::routes(
    [
        'verify' => false,
    ]
);

Route::name('admin.')->prefix('admin')->middleware(['auth', 'can:accessAdmin'])->group(
    function () {
        Route::get('dashboard', 'DashboardController@index')->name('index');
        Route::resource('category', 'CategoryController');
        Route::resource('banner', 'BannerController');
        Route::resource('product', 'ProductController');
        Route::resource('deal', 'DealController');
        Route::resource('user', 'Auth\UserController');
        Route::resource('order', 'OrderController');
        Route::resource('review', 'ReviewController');
    }
);
route::get('product/show/{id}', 'ProductController@show')->name('product.show');
route::get('review', 'ReviewController@index')->name('pro222duct.show');
route::get('product/show-all', 'ProductController@showAll')->name('product.showAll');
route::get('category/show/{id}', 'CategoryController@show')->name('category.show');
Route::resource('account', 'Auth\AccountController');
Route::get('account/{id}/changePass', 'Auth\AccountController@changePass')->name('account.changePass');
Route::post('account/{id}/updatePass', 'Auth\AccountController@updatePass')->name('account.updatePass');
Route::post('add-cart', 'CartController@save_cart')->name('addCart');
Route::get('/search', 'HomeController@search');
Route::get('show-cart', 'CartController@show_cart')->name('showCart');
Route::post('update-qty-cart{id}', 'CartController@update_quantity')->name('updateCart');
Route::get('delete-cart/{rowId}', 'CartController@delete_cart')->name('deleteCart');
Route::get('order/create', 'OrderController@create')->name('order.create');
Route::post('order/store', 'OrderController@store')->name('order.store');
Route::post('review/store', 'ReviewController@store')->name('review.store');
Route::get('/filter', 'HomeController@filter');
Route::get('order/{id}/history', 'OrderController@history')->name('order.history');
Route::post('order/cancel/{id}', 'OrderController@cancel')->name('order.cancel');
Route::get('order/history-detail/{id}', 'OrderController@historyDetail')->name('order.history-detail');

Route::get('/auth/redirect/{provider}', 'SocialController@redirect');
Route::get('/{provider}/callback', 'SocialController@callback');

Route::post('add-wishlist', 'WishlistController@save_wishlist')->name('addWish');
Route::get('show-wishlist/{id}', 'WishlistController@show_wishlist')->name('showWish');
Route::post('delete-wishlist/{rowId}', 'WishlistController@delete_wishlist')->name('deleteWish');

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    protected $primaryKey = 'ban_id';

    protected $fillable = [
        'ban_name',
        'ban_image',
    ];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Banner;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banners = Banner::all();
        return view('banner.view',  compact('banners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('banner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $file = $request -> file('ban_image');
        $fileName = uniqid() . '_' . $file->getClientOriginalName();
        $file->move('images/banners', $fileName);

        Banner::create([
            'ban_image' => $fileName,
            'ban_name'  => $request -> input('ban_name'),
        ]);

        return redirect()->route('admin.banner.index')->with('add_success', trans('admin.message.add_success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($banID)
    {
        $ban = Banner::findOrFail($banID);
        $banners = Banner::all();

        return view('banner.edit', compact('ban', 'banners'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $banID)
    {
        $ban = Banner::findOrFail($banID);

        $file = $request -> file('ban_image');
        $fileName = uniqid() . '_' . $file->getClientOriginalName();
        $file->move('images/banners', $fileName);

       
            $ban -> ban_image = $fileName;
            $ban -> ban_name  = $request -> input('ban_name');
            $ban -> save();

        return redirect()->route('admin.banner.index')->with('update_success', trans('admin.message.update_success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($banID)
    {
        $ban = Banner::findOrFail($banID);
        $ban -> delete();

        return redirect()->route('admin.banner.index')->with('del_success', trans('admin.message.del_success'));
    }
}

resources/views/banner/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>@lang('admin.banners.ban_manage')</h3>
        </div>

       
      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 ">
          <div class="x_panel">
            <div class="x_title">
              <h2>@lang('admin.banners.create')</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <br />
              <form action="{{ route('admin.banner.store') }}" method="POST" enctype="multipart/form-data" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                @csrf
                <div class="item form-group">
                    <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">@lang('admin.banners.ban_image')</label>
                    <div class="col-md-6 col-sm-6 ">
                      <input type="file" id="last-name" name="ban_image" class="form-control">
                    </div>
                </div>
                <div class="item form-group">
                  <label class="col-form-label col-md-3 col-sm-3 label-align" for="first-name">@lang('admin.banners.ban_name') <span class="required">*</span></label>
                  <div class="col-md-6 col-sm-6 ">
                    <input type="text" id="first-name"  name="ban_name" class="form-control ">
                  </div>
                </div>
                <div class="ln_solid"></div>
                <div class="item form-group">
                  <div class="col-md-6 col-sm-6 offset-md-3">
                    <button class="btn btn-primary" type="reset">Reset</button>
                    <button id="submit" type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function(){
      $("button#submit").click(function(){
        var submit = $("input#last-name").val();
        var first_name = $("input#first-name").val();
        var flag = true
        if(submit ==''){
          $("input#last-name").css({"background" : "rgba(255, 147, 146, 0.3)", "border" : "2px solid rgb(255, 0, 0, 0.3)"});
          alert("Bạn chưa thêm file")
          flag = false
        }else{
          $("input#last-name").css({"background" : "rgb(100 216 90 / 30%)", "border" : "2px solid rgb(147 161 146 / 30%)"});
        }

        if(first_name ==''){
          $("input#first-name").css({"background" : "rgba(255, 147, 146, 0.3)", "border" : "2px solid rgb(255, 0, 0, 0.3)"});
          alert("Bạn chưa nhập tên Banner")
          flag = false
        }else{
          $("input#first-name").css({"background" : "rgb(100 216 90 / 30%)", "border" : "2px solid rgb(147 161 146 / 30%)"});
        }
        
        if(flag == true){
          alert("Thêm Thành Công")
          return true
        }
        return false
      })
    })
  </script>
@endsection

resources/views/banner/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>@lang('admin.banners.ban_manage')</h3>
      </div>


    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
          <div class="x_title">
            <h2>@lang('admin.banners.edit')</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <form action="{{ route('admin.banner.update', $ban->ban_id) }}" method="POST" enctype="multipart/form-data" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
              @csrf
              @method('put')
              <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">@lang('admin.banners.ban_image')</label>
                <div class="col-md-6 col-sm-6 ">
                  <input type="file" id="last-name" required="required" name="ban_image" class="form-control" value="{{ $ban->ban_image }}">
                </div>
              </div>
              <div class="item form-group">
                <label class="col-form-label col-md-3 col-sm-3 label-align" for="first-name">@lang('admin.banners.ban_name') <span class="required">*</span></label>
                <div class="col-md-6 col-sm-6 ">
                  <input type="text" id="first-name" required="required" name="ban_name" class="form-control" value="{{ $ban->ban_name }}">
                </div>
              </div>
              <div class="item form-group text-center justify-content-center">
                @if ($ban->ban_image == null)
                <img class="img-thumbnail" style="width: 100px; height:100px;" src="https://logos.textgiraffe.com/logos/logo-name/Cate-designstyle-smoothie-m.png" alt="">
                @else
                <img class="img-thumbnail" style="width: 100px; height:100px;" src="images/banners/{{ $ban->ban_image }}" alt="">
                @endif
              </div>
              <div class="ln_solid"></div>
              <div class="item form-group">
                <div class="col-md-6 col-sm-6 offset-md-3">
                  <button class="btn btn-primary" type="reset">Reset</button>
                  <button id="submit" type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $("button#submit").click(function(){
      var submit = $("input#last-name").val();
      var first_name = $("input#first-name").val();
      var flag = true
      if(submit ==''){
        $("input#last-name").css({"background" : "rgba(255, 147, 146, 0.3)", "border" : "2px solid rgb(255, 0, 0, 0.3)"});
        alert("Bạn chưa thêm file")
        flag = false
      }else{
        $("input#last-name").css({"background" : "rgb(100 216 90 / 30%)", "border" : "2px solid rgb(147 161 146 / 30%)"});
      }

      if(first_name ==''){
        $("input#first-name").css({"background" : "rgba(255, 147, 146, 0.3)", "border" : "2px solid rgb(255, 0, 0, 0.3)"});
        alert("Bạn chưa nhập tên Banner")
        flag = false
      }else{
        $("input#first-name").css({"background" : "rgb(100 216 90 / 30%)", "border" : "2px solid rgb(147 161 146 / 30%)"});
      }
      
      if(flag == true){
        alert("Thêm Thành Công")
        return true
      }
      return false
    })
  })
</script>
@endsection

resources/views/banner/view.blade.php
@extends('layouts.admin')
@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>@lang('admin.banners.ban_manage')</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Danh sách banner</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                {{-- <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="#">Settings 1</a>
                      <a class="dropdown-item" href="#">Settings 2</a>
                    </div> --}}
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                @if (session()->has('del_success'))
                                    <div class="text-success" style="text-shadow: 0 0 1px black;">{{ session()->get('del_success') }}</div>
                                @elseif( session()->has('add_success'))
                                    <div class="atext-success" style="text-shadow: 0 0 1px black;">{{ session()->get('add_success') }}</div>
                                @elseif (session()->has('update_success'))
                                    <div class="text-success" style="text-shadow: 0 0 1px black;">{{ session()->get('update_success') }}</div>
                                @endif
                                <div class="card-box table-responsive">

                                    <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th>@lang('admin.banners.id')</th>
                                                <th>@lang('admin.banners.ban_image')</th>
                                                <th>@lang('admin.banners.ban_name')</th>
                                                <th colspan="2" class="text-center">
                                                    <a href="{{ route('admin.banner.create') }}" class="btn btn-outline-success">@lang('admin.action.create')</a>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($banners as $banner)
                                            <tr>
                                                <td>{{ $banner->ban_id }}</td>
                                                <td>
                                                    @if ($banner->ban_image == null)
                                                    <img class="img-thumbnail" style="width: 100px; height:100px;" src="https://logos.textgiraffe.com/logos/logo-name/Cate-designstyle-smoothie-m.png" alt="">
                                                    @else
                                                    <img class="img-thumbnail" style="width: 100px; height:100px;" src="images/banners/{{ $banner->ban_image }}" alt="">
                                                    @endif
                                                </td>
                                                <td>{{ $banner->ban_name }}</td>
                                                <td class="text-center"><a href="{{ route('admin.banner.edit', $banner->ban_id) }}" class="btn btn-outline-info btn-xs"><i class="fa fa-pencil"></i> @lang('admin.action.edit') </a></td>
                                                <td class="text-center">
                                                    <form action="{{ route('admin.banner.destroy', $banner->ban_id) }}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-outline-danger"><i class="fa fa-trash-o"></i> @lang('admin.action.delete') </button>
                                                    </form>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection